spring:
  datasource:
    url: jdbc:thin://localhost:1521/oracle-container
    username: schema_user
    password: password
    driver-class-name: oracle.jdbc.driver.OracleDriver
  docker:
    compose:
      enabled: true
      file: docker-compose.yaml
