<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.positivinh.playground.spring</groupId>
        <artifactId>playground-spring</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>playground-spring-observability</artifactId>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.opentelemetry.instrumentation</groupId>
                <artifactId>opentelemetry-instrumentation-bom</artifactId>
                <version>2.15.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.micrometer</groupId>
                <artifactId>micrometer-tracing-bom</artifactId>
                <version>1.4.5</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-logging</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-docker-compose</artifactId>
        </dependency>

        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-spring-boot-starter</artifactId>
        </dependency>

        <!-- For Metrics -->
        <!-- For OTLP -->
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-otlp</artifactId>
        </dependency>

        <!-- Brave version -->
        <!-- For Tracing -->
        <!--        <dependency>-->
        <!--            <groupId>io.micrometer</groupId>-->
        <!--            <artifactId>micrometer-tracing-bridge-otel</artifactId>-->
        <!--        </dependency>-->
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-brave</artifactId>
        </dependency>
        <!-- For Latency Visualization -->
        <dependency>
            <groupId>io.zipkin.contrib.otel</groupId>
            <artifactId>encoder-brave</artifactId>
            <version>0.1.0</version>
        </dependency>

        <!-- For pushing logs out -->
        <dependency>
            <groupId>com.github.loki4j</groupId>
            <artifactId>loki-logback-appender</artifactId>
            <version>1.5.2</version>
            <scope>runtime</scope>
        </dependency>
        <!--&lt;!&ndash;         For Metrics &ndash;&gt;-->
        <!--&lt;!&ndash;        <dependency>&ndash;&gt;-->
        <!--&lt;!&ndash;            <groupId>io.micrometer</groupId>&ndash;&gt;-->
        <!--&lt;!&ndash;            <artifactId>micrometer-registry-prometheus</artifactId>&ndash;&gt;-->
        <!--&lt;!&ndash;        </dependency>&ndash;&gt;-->
        <!--&lt;!&ndash;      &ndash;&gt;-->

        <!--&lt;!&ndash;        &lt;!&ndash; Brave version &ndash;&gt;&ndash;&gt;-->
        <!--&lt;!&ndash;        &lt;!&ndash; For Tracing &ndash;&gt;&ndash;&gt;-->
        <!--&lt;!&ndash;        <dependency>&ndash;&gt;-->
        <!--&lt;!&ndash;            <groupId>io.micrometer</groupId>&ndash;&gt;-->
        <!--&lt;!&ndash;            <artifactId>micrometer-tracing-bridge-brave</artifactId>&ndash;&gt;-->
        <!--&lt;!&ndash;        </dependency>&ndash;&gt;-->
        <!--&lt;!&ndash;        <dependency>&ndash;&gt;-->
        <!--&lt;!&ndash;            <groupId>io.zipkin.reporter2</groupId>&ndash;&gt;-->
        <!--&lt;!&ndash;            <artifactId>zipkin-reporter-brave</artifactId>&ndash;&gt;-->
        <!--&lt;!&ndash;            <version>3.4.3</version>&ndash;&gt;-->
        <!--&lt;!&ndash;        </dependency>&ndash;&gt;-->
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
