### GET /playgrounds - no search term

GET {{baseUrl}}/playgrounds

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### GET /playgrounds - matching search term

GET {{baseUrl}}/playgrounds?searchTerm=Default%20play


> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.content.length === 1, "Response does not contain expected element")
    });
%}

### GET /playgrounds - non-matching search tem

GET {{baseUrl}}/playgrounds?searchTerm=💩

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.content.length === 0, "Response is not empty")
    });
%}
