
### GET /actuator

GET {{baseUrl}}/actuator

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.hasOwnProperty("_links"),  "unexpected response body")
    });
%}



### GET /actuator/health

GET {{baseUrl}}/actuator/health

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.status === 'UP',  "unexpected response body")

    });
%}


