management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: # https://docs.spring.io/spring-boot/reference/actuator/endpoints.html
          #          - * # enable all actuator endpoints
          - health
          - info
          - beans
          - conditions
          - configprops
          - env
          - logfile # does not work ?
          - loggers
          - metrics
          - scheduledtasks
          - httpexchanges
          - metrics
          - mappings
          - custom
  endpoint:
    health:
      group:
        group-name:
          show-components: always
          show-details: always
          include:
            - diskSpace
            - ping
            - custom
            - livenessState
      show-components: always #when-authorized
      roles:
        - ENDPOINT_ADMIN
    logfile:
      enabled: true
      external-file: target/application.log
    env:
      show-values: always
    configprops:
      show-values: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    mongo:
      enabled: true
    livenessstate:
      enabled: true
logging:
  file:
    path: target/application.log
