management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
#          - * # enable all actuator endpoints
          - health
          - info
          - beans
          - conditions
          - configprops
          - env
          - logfile # does not work ?
          - loggers
          - metrics
          - scheduledtasks
          - httpexchanges
          - metrics
          - mappings
          - custom
  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always
          include:
            - diskSpace
            - ping
    logfile:
      enabled: true
      external-file: target/application.log
    env:
      show-values: always
    configprops:
      show-values: always

logging:
  file:
    path: target/application.log
